---
title: "Instacart Grocery Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

# Load and sample data
data("instacart")
instacart_sample <- instacart |> 
  sample_n(10000) |>  # Random sample
  filter(!is.na(department))  # Remove NA values
```

------------------------------------------------------------------------
## Scatterplot

```{r}
plot_ly(instacart_sample, 
        x = ~order_hour_of_day, 
        y = ~order_number, 
        type = "scatter", 
        mode = "markers",
        color = ~aisle, 
        alpha = 0.6) |> 
  layout(title = "Order Hour vs. Order Number by Aisle",
         xaxis = list(title = "Hour of Day (0-23)"),
         yaxis = list(title = "Order Sequence Number"),
         legend = list(title = list(text = "Aisle")))
```

------------------------------------------------------------------------
## Bar Plot
```{r}
top_aisles <- instacart_sample |> 
  count(aisle) |> 
  top_n(10, n) |> 
  mutate(aisle = fct_reorder(aisle, n))

plot_ly(top_aisles, 
        x = ~aisle, 
        y = ~n, 
        type = "bar", 
        color = ~aisle,
        showlegend = FALSE) |> 
  layout(title = "Top 10 Aisles Based on Count of Orders",
         xaxis = list(title = "Name of Aisle", tickangle = -45),
         yaxis = list(title = "Number of Orders"))
```


------------------------------------------------------------------------
## Box Plot
```{r}
plot_ly(instacart_sample, 
        y = ~add_to_cart_order, 
        type = "box", 
        color = ~department,
        boxpoints = "outliers") |> 
  layout(title = "Add-to-Cart Distribution Across Departments",
         yaxis = list(title = "Position in Cart (1 = First Added)"),
         xaxis = list(title = "Department"),
         showlegend = TRUE)
```

